baseURL = ''
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

disqusShortname = 'ruilinp'

[params]
themeColor = "blue"

fullWidthTheme = true
showMenuItems = 0

centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Ruilin's Blog"
    subtitle = "Ruilin Peng's personal blog powered by Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "[ruilin@archlinux blog]$"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"

    [[languages.en.menu.main]]
        identifier = "certificates"
        name = "Certificates"
        url = "/certificates"

    [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"

    [[languages.en.menu.main]]
        identifier = "back"
        name = "Back"
        url = "/"
